load("@rules_proto//proto:defs.bzl", "proto_library")

licenses(["notice"])  # Apache 2

proto_library(
  name = "common_protocol_proto_lib",
  srcs = ["Common.proto"],
  visibility = ["//visibility:public"],
)
